name: chores

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    # note: this will keep updating the existing branch
    - cron: "*/15 10-14 * * 0,6"
    - cron: "0 14 * * 1-5"

jobs:
  fix-typos:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run tests
        run: echo make test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: fix-typos
          delete-branch: false # Delete the branch when closing pull requests, and when undeleted after merging.
          token: ${{ secrets.GITHUB_TOKEN }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "chore(docs): fix typos"
          commit-message: "chore(docs): fix typos"
